### ISSUE TITLE
Where did the "ga" definition

### ISSUE THREAD

**Issue by Rachelin** [chinchang/vuejsfire-hackathon-starter#1]
Hi @chinchang 
First of all, please accept my thankfulness. With reading this project help me understand how did firebase work. Here exist big "BUT". I can not find where did the "ga" function defined?

In the file of "main.js", line to 18.

```
router.afterEach(function (transition) {
  if (transition.to.defaultTitle !== false) {
    document.title = 'VueFire Hackathon Starter';
  }
  ga('set', 'page', transition.to.path);
  ga('send', 'pageview');
});
```

What did the ga do? Why you need set the page?

**Comment by chinchang** [comment]
`ga` is Google Analytics - used to log page metrics. The definition of `ga` is in `index.html` https://github.com/chinchang/vuejsfire-hackathon-starter/blob/master/index.html#L78

**Comment by Rachelin** [comment]
@chinchang  Thank you, I got it
